version: '3.8'
services: 
  solr:
    image: solr:9.0.0
    container_name: solr
    hostname:  solr
    ports:
      - 8983:8983
    environment:
      SOLR_HOST: solr
      JVM_OPTS: '-Xms1024m -Xmx1024m'
      SOLR_JAVA_MEM: '-Xms1024m -Xmx1024m'
    volumes:
      - ./docker/solr:/var/solr/data


  #awsglue:
  #  image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
  #  container_name: awsglue
  #  tty: true

  notebooks:
    build:
      context: notebooks/.
      dockerfile: Dockerfile
    container_name: notebooks
    ports:
      - 7077:7077 # Spark Master
      - 8082:8080 # Spark Master UI - 8082 less likely to conflict
      - 8081:8081 # Spark Worker UI
      - 4040:4040 # Spark UI
      - 4041:4041 # Spark UI
      - 8889:8889 # Jupyter Notebook UI
      #- 2345:2345 # Search Webserver
    depends_on:
      - solr
       #networks:
       #- solr-data-science

    environment:
      SOLR_HOST: 'showntell-solr'
    volumes:
     - type: bind
       source: "./notebooks/"
       target: "/tmp/notebooks/"
